# Generated by Django 4.2.3 on 2023-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gu', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
